---
measurement_id:
  description: "The measurement ID to retrive from RIPE Atlas"
  type: "integer"
  required: true

probes:
  description: "The probes to use when querying the measurement ID"
  type: "array"
  required: false
  items:
    type: "integer"
    required: true
