---
html_table_class:
  description: "Class for table in HTML output."
  type: "string"
  required: true

config_repo:
  description: "Git repository where configurations are located"
  type: "string"
  required: false

devices:
  description: "List of devices to map the device hostname with the driver and credentials"
  required: true
  type: "array"
  items:
    type: "object"
    required: true
    properties:
      hostname:
        description: "Hostname for the device"
        type: "string"
        required: true
      port:
        description: "Port for the device"
        type: "integer"
        required: false
      driver:
        description: "Driver for the device"
        type: "string"
        required: true
      credentials:
        description: "Credentials group used to login to the device"
        type: "string"
        required: true

credentials:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/cred_group"
  additionalProperties: false

cred_group:
  type: "object"
  properties:
    username:
      description: "Username for network device"
      type: "string"
      required: true
    password:
      description: "Password for network device"
      type: "string"
      secret: true
      required: true
  additionalProperties: false
