---
name: "host_at_least_partially_unreachable"
pack: "atlas"
description: "Triggers when the host became at least partially unreachable"
enabled: true

trigger:
    type: "atlas.HostPartiallyUnreachable"

action:
  ref: "core.local"
  parameters:
    cmd: "echo \"probe {{trigger.prb_id}} detected host {{trigger.dst_addr}} to have become unreachable\""
