---
name: "probes_disco_rules"
pack: "atlas"
description: "Rules for firing probes disco events"
enabled: true

trigger:
    type: "atlas.probes_disco"
    parameters: {}

action:
    ref: "core.local"
    parameters:
      cmd: "echo \"probe with id {{trigger.prb_id}} {{trigger.event}}ed.\" >> /var/log/prb_evnts.log"